const respostas = [
    {resposta:"UMA MALDIÇÃO CIGANA."},
    {resposta:"MAOMÉ (LOUVADO SEJA SEU NOME)"},
    {resposta:"UM MOMENTO DE SILÊNCIO."},
    {resposta:"A MERDA DA MINHA VIDA."},
    {resposta:"SEXO SURPRESA."},
    {resposta:"UM FESTIVAL DA LINGUIÇA."},
    {resposta:"UM HOMEM À BEIRA DO ORGASMO."},
    {resposta:"X-TUDÃO."},
    {resposta:"UM POLICIAL HONESTO SEM NADA A PERDER."},
    {resposta:"COZINHAR ELES VIVOS, PORQUE O MEDO ADICIONA SABOR."},
    {resposta:"BEBER SOZINHO."},
    {resposta:"ESCASSEZ DE COMIDA."},
    {resposta:"ACIDENTALMENTE ENVIAR NUDES PARA A SUA MÃE."},
    {resposta:"ACIDENTALMENTE RECEBER NUDES DA SUA MÃE."},
    {resposta:"SUA IRMÃ AQUELA GOSTOSA."},
    {resposta:"SUA MÃE."},
    {resposta:"FAKE NEWS."},
    {resposta:"MÃO FURADA."},
    {resposta:"BACTÉRIA CARNÍVORA."},
    {resposta:"MÃE RÚSSIA. "},
    {resposta:"MÚLTIPLAS FACADAS."},
    {resposta:"ERVA PARA AUMENTAR A LIBIDO."},
    {resposta:"MEDIÇÃO DE PÊNIS. "},
    {resposta:"SUJAR-SE."},
    {resposta:"GOZAR EM 20 SEGUNDOS."},
    {resposta:"NÃO DAR A MÍNIMA PARA O TERCEIRO MUNDO."},
    {resposta:"UM CHINÊS ESCONDIDO NO MEU PORTA-MALA."},
    {resposta:"ABUSO INFANTIL."},
    {resposta:"SEXTING. "},
    {resposta:"CORDÃO ANAL COM NÓDULOS E ALÇA DE SEGURANÇA."},
    {resposta:"TRANSMUTAÇÃO CORPÓREA."},
    {resposta:"VÍTIMAS CIVIS."},
    {resposta:"ATRIZES PORNÔ. "},
    {resposta:"SONHOS MOLHADOS."},
    {resposta:"COITO INTERROMPIDO."},
    {resposta:"CRIANCINHAS. "},
    {resposta:"MIJAR EM TUDO QUE VOCÊ AMA."},
    {resposta:"HOMEM DE FERRO."},
    {resposta:"ESTUPRAR E SAQUEAR."},
    {resposta:"2 GIRLS, 1 CUP. "},
    {resposta:"CARNE DE CAVALO."},
    {resposta:"72 VIRGENS. "},
    {resposta:"A REPÚBLICA CISPLATINA."},
    {resposta:"UM CHAPÉU SUPER TRANSADO."},
    {resposta:"FUZILAMENTO. "},
    {resposta:"NECROFILIA. "},
    {resposta:"UM PARADOXO DE VIAGEM NO TEMPO."},
    {resposta:"ROUBO DE TÚMULOS."},
    {resposta:"FETICHE EM PÉS."},
    {resposta:"CINTARALHO."},
    {resposta:"PLUG ANAL."},
    {resposta:"UM PELO PUBIANO."},
    {resposta:"AUTÊNTICA COZINHA MEXICANA."},
    {resposta:"CLAREAMENTO ANAL."},
    {resposta:"FRATERNIDADES JUDIAS."},
    {resposta:"CINTILANTE. MÚLTIPLOS FERIMENTOS DE FACA."},
    {resposta:"COTAS RACIAIS."},
    {resposta:"CONSULTORES. "},
    {resposta:"PINTO DE BORRACHA. "},
    {resposta:"UM CONSOLO PRETO. "},
    {resposta:"O PROFETA MAOMÉ(QUE ALÁ O ABENÇOE)."},
    {resposta:"FAZER AQUILO NA BUNDA."},
    {resposta:"DÍVIDA MONSTRUOSA."},
    {resposta:"RASPAR O SACO COM UMA FACA."},
    {resposta:"EQUIPAR MENDIGOS COM PONTOS DE ACESSO WI-FI."},
    {resposta:"ENSINAR UM ROBÔ A AMAR."},
    {resposta:"PROBLEMAS COM O PAI NA INFÂNCIA."},
    {resposta:"EU. "},
    {resposta:"SER FODA."},
    {resposta:"BALBÚRDIA. "},
    {resposta:"BÓRIS, A MARRETA DE AMOR SOVIÉTICA."},
    {resposta:"UM MOINHO DE VENTO CHEIO DE CADÁVERES."},
    {resposta:"SUBJUGAR UM URSO PARDO E TORNÁ-LO SUA ESPOSA."},
    {resposta:"TODDYNHO."},
    {resposta:"COTAS RACIAIS. "},
    {resposta:"CHICOTEAR UM ESCRAVO DESOBEDIENTE."},
    {resposta:"VESTIR ROUPA ÍNTIMA AO AVESSO PRA ECONOMIZAR UMA LAVADA."},
    {resposta:"DEIXAR O LUSTRE CAIR SOBRE SEUS INIMIGOS ENQUANTO A OUTRA PONTA DA CORDA TE LANÇA PARA CIMA."},
    {resposta:"A MISTURA DAS RAÇAS."},
    {resposta:"UM RAIO DA MORTE."},
    {resposta:"O EX-PRESIDENTE MICHEL TEMER."},
    {resposta:"ESTUPIDEZ INCONCEBÍVEL."},
    {resposta:"TETO DE VIDRO."},
    {resposta:"HÉTERO TOP."},
    {resposta:"NUDEZ FRONTAL. "},
    {resposta:"LUZ DO SOL E ARCO-ÍRIS."},
    {resposta:"UM CONGELADOR CHEIO DE ÓRGÃOS."},
    {resposta:"INJEÇÕES HORMONAIS."},
    {resposta:"A VIOLAÇÃO DOS NOSSOS MAIS BÁSICOS DIREITOS."},
    {resposta:"O SONHO AMERICANO."},
    {resposta:"PÔR UM OVO. "},
    {resposta:"BOTAR O PAU NA MESA."},
    {resposta:"BARRIGA DE CHOPP."},
    {resposta:"ASSISTIR TV GLOBINHO PELADO(A)."},
    {resposta:"OS TERRORISTAS. "},
    {resposta:"QUANDO VOCÊ PEIDA E SAI MAIS DO QUE DEVIA."},
    {resposta:"FINGIR QUE SE IMPORTA."},
    {resposta:"A MINORIA. "},
    {resposta:"PEGAR DE VOLTA O QUE FOI DADO."},
    {resposta:"PAGAR MICO EM PÚBLICO."},
    {resposta:"A ELITE BRANCA. "},
    {resposta:"COMPARTILHAR AGULHAS."},
    {resposta:"EMOÇÕES. "},
    {resposta:"COMER UM ANÃO. "},
    {resposta:"PREPÚCIO."},
    {resposta:"MELECA DE NARIZ. "},
    {resposta:"ASSASSINATO VEICULAR."},
    {resposta:"SOLOS DE SAXOFONE."},
    {resposta:"A INEVITÁVEL MORTE DO UNIVERSO."},
    {resposta:"A DITADURA MILITAR."},
    {resposta:"ITALIANOS."},
    {resposta:"O MILAGRE DO PARTO."},
    {resposta:"AUTISMO. "},
    {resposta:"UM FETO."},
    {resposta:"O APOCALIPSE. "},
    {resposta:"UM PINTO GRANDE E NEGRO."},
    {resposta:"DISPARAR UMA ESPINGARDA PARA O ALTO ENQUANTO TREPA COM UMA CABRA QUE ESTÁ AOS BERROS."},
    {resposta:"PASSAR O RODO. "},
    {resposta:"EDITAR A WIKIPÉDIA PARA GANHAR UMA DISCUSSÃO."},
    {resposta:"GUGU."},
    {resposta:"UMA PENTADA VIOLENTA."},
    {resposta:"UM RIFLE DE ASSALTO."},
    {resposta:"AMPUTADOS."},
    {resposta:"NO GRAU. "},
    {resposta:"FICAR PUTO A PONTO DE TER UMA EREÇÃO."},
    {resposta:"EUGENIA."},
    {resposta:"O PRIVILÉGIO DE SER BRANCO."},
    {resposta:"INCESTO. "},
    {resposta:"O STATUS DE MINHA RELAÇÃO."},
    {resposta:"DEVERES DA ESPOSA."},
    {resposta:"UM PINTO MAIOR E MAIS NEGRO."},
    {resposta:"O MAIOR E MAIS NEGRO PINTO."},
    {resposta:"NICOLAS CAGE."},
    {resposta:"RECATADA. "},
    {resposta:"ABELHAS."},
    {resposta:"UMA CANETA."},
    {resposta:"UMA VIAGEM PARA PELOTAS."},
    {resposta:"FAZER A COISA CERTA."},
    {resposta:"EROTISMO BASEADO EM HARRY POTTER."},
    {resposta:"DESODORANTE AXE. "},
    {resposta:"ESCRAVIZAR A PRÓPRIA FAMÍLIA."},
    {resposta:"FACULDADE."},
    {resposta:"O SANGUE DE CRISTO."},
    {resposta:"UM LINDO NAZICÓRNIO."},
    {resposta:"SÓ A CABECINHA."},
    {resposta:"FICAR BÊBADO AO BOCHECHAR ANTI-SÉPTICO BUCAL."},
    {resposta:"HORRIVEIS ACIDENTES CAUSADO POR DEPILAÇÃO A LASER."},
    {resposta:"SER UM IMBECIL COM CRIANÇAS."},
    {resposta:"NAZISTAS."},
    {resposta:"BATMAN! "},
    {resposta:"PEIDO MOLHADO. "},
    {resposta:"200 GRAMAS DE DOCE HEROÍNA"},
    {resposta:"PRETA MEXICANA."},
    {resposta:"AGRICULTURA. "},
    {resposta:"STEPHEN HAWKING DIZENDO COISAS OBSCENAS."},
    {resposta:"UM MONGOLÓIDE VIGOROSO."},
    {resposta:"VER A VOVÓ PELADA."},
    {resposta:"PAIS MORTOS."},
    {resposta:"ROUBAR UM IDOSO."},
    {resposta:"SELEÇÃO NATURAL. "},
    {resposta:"ESCONDER UMA EREÇÃO."},
    {resposta:"PERMANÊNCIA DO OBJETO."},
    {resposta:"ABORTO CLANDESTINO."},
    {resposta:"MAMILOS. "},
    {resposta:"UMA FACA AK-47. "},
    {resposta:"TRAIR UM AMIGO. "},
    {resposta:"THAIS CARLA MAGRA. "},
    {resposta:"VENDER CRIANÇAS NA DEEP WEB. "},
    {resposta:"POLEGARES OPOSITORES."},
    {resposta:"COMER TODOS OS DOCES QUE DEVERIAM SER VENDIDOS NA CAMPANHA DE CARIDADE."},
    {resposta:"UM ALUNO DE HUMANAS."},
    {resposta:"QUESTÕES RACISTAS EM VESTIBULAR."},
    {resposta:"OS BRAÇOS DA DILMA."},
    {resposta:"NUDEZ FRONTAL COMPLETA."},
    {resposta:"FALAR ABOBRINHA."},
    {resposta:"O JOGO WORLD OF WARCRAFT."},
    {resposta:"LEAGUE OF LEGENDS."},
    {resposta:"A EX-NAMORADA DO AMIGO."},
    {resposta:"MOTOSSERRAS."},
    {resposta:"KU KLUX KLAN."},
    {resposta:"COBIÇAR A MULHER DO PRÓXIMO."},
    {resposta:"HERPES LABIAL. "},
    {resposta:"SILVIO SANTOS."},
    {resposta:"OBESIDADE. "},
    {resposta:"UM ALUNO DE EXATAS. "},
    {resposta:"CONCURSOS DE BELEZA PARA CRIANÇAS."},
    {resposta:"UM CLIPE HOMO-ERÓTICO SOBRE VOLEIBOL."},
    {resposta:"GANDALF. "},
    {resposta:"EXPLOSÕES."},
    {resposta:"TÉTANO. "},
    {resposta:"MASTURBAR O PÊNIS ALHEIO."},
    {resposta:"CHEIRAR COLA."},
    {resposta:"EXIBIÇÃO PARA FINS DE ACASALAMENTO."},
    {resposta:"O ARREBATAMENTO. "},
    {resposta:"REPRESSÃO."},
    {resposta:"TORÇÃO TESTICULAR."},
    {resposta:"SER UM BABACA ATIVO-AGRESSIVO."},
    {resposta:"BOA NOITE, CINDERELA."},
    {resposta:"BUFFET DE CAMARÃO LIVRE POR R$4,99."},
    {resposta:"JOSEF STALIN. "},
    {resposta:"MINHA VAGINA."},
    {resposta:"FEIJOADA. "},
    {resposta:"MIJAR EM ALGUÉM PARA MARCAR TERRITÓRIO."},
    {resposta:"BIQUINI FIO-DENTAL."},
    {resposta:"KANYE WEST. "},
    {resposta:"ROUBAR UM BANCO DE ESPERMA."},
    {resposta:"CHACINA."},
    {resposta:"QUEIJO QUENTE. "},
    {resposta:"UM TUMOR NO CÉREBRO."},
    {resposta:"DAR-SE 110%."},
    {resposta:"ATAQUES DE VELOCIRAPTOR."},
    {resposta:"TRANSAR NA REUNIÃO FAMILIAR."},
    {resposta:"SUA ALTEZA REAL, RAINHA ELIZABETH II."},
    {resposta:"TIRAR A CAMISA. "},
    {resposta:"DIA DA CONSCIÊNCIA NEGRA."},
    {resposta:"MAIS OU MENOS."},
    {resposta:"ESMEGMA. "},
    {resposta:"BEBÊS MORTOS. "},
    {resposta:"O CAMINHO DE SANTIAGO."},
    {resposta:"ALCOOLISMO. "},
    {resposta:"MÚSICA NEW AGE. "},
    {resposta:"SER MARGINALIZADO."},
    {resposta:"UM CARA DE MEIA IDADE ANDANDO DE PATINS."},
    {resposta:"FURAR CAMISINHAS."},
    {resposta:"GOBLINS. "},
    {resposta:"ONLY FANS. "},
    {resposta:"OS RAIOS DE SENTIMENTOS BONS DOS URSINHOS CARINHOSOS."},
    {resposta:"EMPANTURRAR-SE E PURGAR-SE."},
    {resposta:"TERMONUCLEAR. "},
    {resposta:"O REVERENDO DR.MARTIN LUTHER KING, JR."},
    {resposta:"PIRULITOS GIGANTES."},
    {resposta:"PROBLEMAS DE PRIMEIRO MUNDO."},
    {resposta:"AUTO-REPUGNÂNCIA."},
    {resposta:"DEUS. "},
    {resposta:"MINHA ALMA. "},
    {resposta:"CRIANÇAS NA COLEIRA."},
    {resposta:"A INTERNET INTEIRA. "},
    {resposta:"UMA DESOLAÇÃO."},
    {resposta:"PRELIMINARES MEIA-BOCA."},
    {resposta:"HARRY POTTER."},
    {resposta:"VIKINGS."},
    {resposta:"A BÍBLIA SAGRADA. "},
    {resposta:"PUBERDADE. "},
    {resposta:"GOSTOSAS."},
    {resposta:"PORNÔ. "},
    {resposta:"CRIANÇAS COM CÂNCER NO RETO. "},
    {resposta:"FINGIR SER UM CACHORRO E CAGAR NA SALA. "},
    {resposta:"SEDUÇÃO."},
    {resposta:"ESTAR EM CHAMAS."},
    {resposta:"FOTOS DE PINTOS NÃO SOLICITADAS."},
    {resposta:"COMPLEXO DE ÉDIPO."},
    {resposta:"GRAVIDEZ NA ADOLESCÊNCIA."},
    {resposta:"GANSOS."},
    {resposta:"GANDHI. "},
    {resposta:"DOCE, DOCE VINGANÇA."},
    {resposta:"AQUECIMENTO GLOBAL."},
    {resposta:"DEIXAR UMA MENSAGEM DE VOZ ESQUISITA."},
    {resposta:"DESCOBRIR QUE O PÊNIS DA SUA NAMORADA É MAIOR QUE O SEU."},
    {resposta:"VOADORA. "},
    {resposta:"AS MARAVILHAS DO ORIENTE."},
    {resposta:"HOT POCKETS SADIA."},
    {resposta:"FUNCIONÁRIOS DO SERVIÇO DE ATENDIMENTO AO CLIENTE."},
    {resposta:"PRÉ-ADOLESCENTES. "},
    {resposta:"FAZER BEICINHO."},
    {resposta:"UMA EREÇÃO QUE DURA MAIS QUE QUATRO HORAS."},
    {resposta:"ABRAÇAR A AVÓ NO MEIO DE UMA EREÇÃO."},
    {resposta:"HOMICÍDIO EM DIREÇÃO VEICULAR."},
    {resposta:"MINHA GENITÁLIA. "},
    {resposta:"UM PRÍNCIPE NIGERIANO."},
    {resposta:"SUFRÁGIO FEMININO."},
    {resposta:"SEU CÚ."},
    {resposta:"VAZAMENTO ANAL. "},
    {resposta:"ENFIAR O DEDO NO CÚ. "},
    {resposta:"UM PRESERVATIVO DEFEITUOSO."},
    {resposta:"FODA-SE. "},
    {resposta:"DISFUNÇÃO ERÉTIL. "},
    {resposta:"SESSÃO DA TARDE."},
    {resposta:"FILHO DA PUTA. "},
    {resposta:"TER DOIS ÂNUS NO LUGAR DOS OLHOS."},
    {resposta:"CRIANÇAS AFRICANAS."},
    {resposta:"PEGAR MULHER NA"},
    {resposta:"CLÍNICA DE ABORTO. "},
    {resposta:"SE MASTURBAR COM COLA."},
    {resposta:"A BOATE KISS."},
    {resposta:"CIÊNCIA. "},
    {resposta:"TER GONORREIA. "},
    {resposta:"DUNGEONS & DRAGONS."},
    {resposta:"BARACK OBAMA."},
    {resposta:"SEXO ORAL NÃO RECÍPROCO."},
    {resposta:"MINAS TERRESTRES. "},
    {resposta:"ASIÁTICOS QUE NÃO SÃO BONS EM MATEMÁTICA."},
    {resposta:"AVES QUE NÃO VOAM."},
    {resposta:"UMA FISSURA ANAL."},
    {resposta:"HOMENS JAPONESES IDOSOS."},
    {resposta:"UMA BOA CHEIRADA."},
    {resposta:"TROCA DE GENTILEZAS."},
    {resposta:"AFOGAMENTO SIMULADO."},
    {resposta:"AFOGAR COM ESPERMA."},
    {resposta:"FICAR SEM SÊMEN."},
    {resposta:"HETERONORMATIVIDADE."},
    {resposta:"AQUELA TORA DE CHÁ."},
    {resposta:"ESTAR COM O PAU COÇANDO."},
    {resposta:"SEPARAR O MAR VERMELHO."},
    {resposta:"CAFÉ DA MANHÃ BALANCEADO."},
    {resposta:"O SUL. "},
    {resposta:"UM ANÃO."},
    {resposta:"FACULDADES. "},
    {resposta:"PROTEGER SUA VIRGINDADE."},
    {resposta:"FILHOTE DE POMBA."},
    {resposta:"LITERALMENTE ROUBAR DOCE DE CRIANÇA."},
    {resposta:"SE MASTURBAR PARA UM PERSONAGEM DE NARUTO."},
    {resposta:"O ACRE."},
    {resposta:"LAR, DOCE LAR. "},
    {resposta:"ALCOOLISMO. "},
    {resposta:"TACAR BOMBA EM UM ASILO. "},
    {resposta:"BUZINAR EM FRENTE AO HOSPITAL. "},
    {resposta:"ARNOLD SCHWARZENEGGER."},
    {resposta:"DE VOLTA PRA MINHA TERRA."},
    {resposta:"PIADAS SOBRE O HOLOCAUSTO NA HORA ERRADA."},
    {resposta:"SEXO ORAL NO CARRO."},
    {resposta:"BANHEIRA DO GUGU."},
    {resposta:"SER NOTADO PELO SENPAI."},
    {resposta:"BARRIGA TANQUINHO."},
    {resposta:"UM ARRANHÃO NA BUNDA MANTIDO EM SEGREDO."},
    {resposta:"A SUA WAIFU. "},
    {resposta:"HOMICÍDIO CULPOSO."},
    {resposta:"BILHETES PASSIVO-AGRESSIVOS NO TRABALHO."},
    {resposta:"QUASE DAR DINHEIRO PARA UM MENDIGO."},
    {resposta:"PÃO NA CHAPA."},
    {resposta:"O TIME DE GINÁSTICA CHINÊS."},
    {resposta:"VER AS COISAS DA PERSPECTIVA DO HITLER."},
    {resposta:"UM LEÃO DE ZOOLÓGICO DEPRIMIDO."},
    {resposta:"DEPENDER DO SUS. "},
    {resposta:"EXATAMENTE O QUE VOCÊ ESPERAVA."},
    {resposta:"TARJA PRETA."},
    {resposta:"CORNO MANSO."},
    {resposta:"CORTAR DE GIRO PARA EVITAR SER CORNO."},
    {resposta:"MIJAR UM POUCO. "},
    {resposta:"UMA IDENTIDADE DE GÊNERO QUE SÓ PODE SER EXPLICADA ATRAVÉS DE POESIA."},
    {resposta:"UM SACO DE FEIJÕES MÁGICOS."},
    {resposta:"CAPITÃO NASCIMENTO LEVANDO BRONCA DA SOGRA."},
    {resposta:"DIZER 'EU TE AMO'."},
    {resposta:"MÁS DECISÕES AO LONGO DA VIDA."},
    {resposta:"POLUÇÃO NOTURNA. "},
    {resposta:"O QUE JESUS FARIA. "},
    {resposta:"MINHA VIDA SEXUAL."},
    {resposta:"OS JUDEUS. "},
    {resposta:"MEU FILHO INÚTIL. "},
    {resposta:"UMA TARTARUGA MORDISCANDO A PONTA DO SEU PÊNIS."},
    {resposta:"MINHAS CURVAS. "},
    {resposta:"SER UM PUTA DUM FEITICEIRO."},
    {resposta:"UMA DETONAÇÃO TERMONUCLEAR."},
    {resposta:"COISAS PODEROSAS. "},
    {resposta:"SER LOUVADO COMO O UM DEUS VERDADEIRO."},
    {resposta:"O CLITÓRIS."},
    {resposta:"PISCAR PARA IDOSOS."},
    {resposta:"UM ASSASSINATO CRUEL."},
    {resposta:"O BIG BANG."},
    {resposta:"REPÓRTERES DE PROGRAMA HUMORÍSTICO."},
    {resposta:"PEIDAR E FUGIR. "},
    {resposta:"MINAS TERRESTRES."},
    {resposta:"UMA CARÍCIA SUAVE NA PARTE INTERNA DA COXA."},
    {resposta:"FRICÇÃO. "},
    {resposta:"AMIGOS QUE COMEM TODO O LANCHE."},
    {resposta:"TENSÃO SEXUAL. "},
    {resposta:"O MEDO EM SI. "},
    {resposta:"CABRAS COMENDO LATAS."},
    {resposta:"O FRUTO PROIBIDO. "},
    {resposta:"TOCAR A CAMPAINHA E SAIR CORRENDO."},
    {resposta:"A DANÇA DA FADA AÇUCARADA."},
    {resposta:"ESQUELETO. "},
    {resposta:"MUDANDO A OPINIÃO DE ALGUÉM COM FATOS E LÓGICA."},
    {resposta:"CACHAÇA."},
    {resposta:"CHURRASCO NA LAJE."},
    {resposta:"ASIÁTICOS. "},
    {resposta:"CARNE HUMANA."},
    {resposta:"SER RICO. "},
    {resposta:"UM BANDO DE IDIOTAS JOGANDO UM JOGO DE CARTAS ONLINE AO INVÉS DE INTERAGIREM COMO HUMANOS NORMAIS."},
    {resposta:"TEMPO PRA MIM."},
    {resposta:"UMA HISTÓRIA ININTERRUPTA DE IMPERIALISMO E EXPLORAÇÃO."},
    {resposta:"SEM TEMPO, AMIGO."},
    {resposta:"REPUBLICANOS. "},
    {resposta:"UM NOVO TIPO DE PORNÔ."},
    {resposta:"TÚNEIS CLANDESTINOS."},
    {resposta:"UM ANTÍLOPE FLATULENTO."},
    {resposta:"VIKINGS. "},
    {resposta:"NADA ACONTECE, FEIJOADA."},
    {resposta:"IVETE SANGALO. "},
    {resposta:"GOLDEN SHOWER. "},
    {resposta:"AI QUE DELÍCIA, CARA!"},
    {resposta:"ACARICIAR ALGUÉM SEM PERMISSÃO."},
    {resposta:"BOQUETES PARA TODOS."},
    {resposta:"TÁ PEGANDO FOGO BICHO!"},
    {resposta:"PILOTOS KAMIKAZE. "},
    {resposta:"UMA CAMISINHA DEFEITUOSA."},
    {resposta:"DOMINGO LEGAL!"},
    {resposta:"REYNALDO GIANECCHINI."},
    {resposta:"PIADAS INOPORTUNAS SOBRE O HOLOCAUSTO."},
    {resposta:"A AGENDA HOMOSSEXUAL."},
    {resposta:"A METADE NEGRA DE BARACK OBAMA."},
    {resposta:"UM MAR DE PROBLEMAS."},
    {resposta:"O MEXICANO QUE TRABALHA DURO."},
    {resposta:"PERDA PENIANA SÚBITA."},
    {resposta:"UM PERNILONGO NO SEU OUVIDO."},
    {resposta:"HISTÓRIAS DE LENHADOR."},
    {resposta:"DAR O ANEL."},
    {resposta:"UM FALCÃO ENCAPUZADO."},
    {resposta:"FICAR OFENDIDO COM QUALQUER COISA."},
    {resposta:"A VOZ DO MORGAN FREEMAN."},
    {resposta:"COROINHAS. "},
    {resposta:"MENTIR NA ENTREVISTA DE EMPREGO. "},
    {resposta:"CHUPAR O DEDÃO DO PÉ. "},
    {resposta:"ENCHER O ÂNUS DE UM HOMEM COM CONCRETO."},
    {resposta:"MULHERES EM COMERCIAIS DE IOGURTE."},
    {resposta:"O 11 DE SETEMBRO. "},
    {resposta:"COMERCIAL DE MARGARINA."},
    {resposta:"NAMORAR UMA PROSTITUTA."},
    {resposta:"FICAR TÃO NERVOSO A PONTO DE TER UMA EREÇÃO."},
    {resposta:"A METADE BRANCA DE BARACK OBAMA."},
    {resposta:"MORRER SOZINHO."},
    {resposta:"CHOROU DE RIR. "},
    {resposta:"COXINHAS. "},
    {resposta:"AUMENTO PENIANO NATURAL."},
    {resposta:"AMOSTRA GRÁTIS. "},
    {resposta:"UM PAÍS DA EUROPA. "},
    {resposta:"SER UM FEITICEIRO."},
    {resposta:"UM GRANDE ESTARDALHAÇO POR NADA."},
    {resposta:"UM MÍMICO TENDO UM DERRAME."},
    {resposta:"FAZER A COISA CERTA."},
    {resposta:"SOCAR PESSOAS PARA ESTABELECER DOMINÂNCIA."},
    {resposta:"PIERCINGS GENITAIS."},
    {resposta:"O JEITINHO BRASILEIRO."},
    {resposta:"NICOLAS CAGE. "},
    {resposta:"TRAVESTIS QUE NÃO PARECEM."},
    {resposta:"LACTAÇÃO. "},
    {resposta:"BRIGAS DE TRAVESSEIRO SENSUAIS."},
    {resposta:"PAZ MUNDIAL. "},
    {resposta:"A FÚRIA DE VLADIMIR PUTIN."},
    {resposta:"BOLAS."},
    {resposta:"ROBOCOP. "},
    {resposta:"PESSOAS BRANCAS. "},
    {resposta:"VOVÓ."},
    {resposta:"SEM-VERGONHICE."},
    {resposta:"ABACATE."},
    {resposta:"JUSTIN BIEBER. "},
    {resposta:"NAZISTAS. "},
    {resposta:"FRICÇÃO."},
    {resposta:"OOMPA-LOOMPAS. "},
    {resposta:"UMA VIDA REPLETA DE TRISTEZA."},
    {resposta:"ESTRAGA-FESTA."},
    {resposta:"CANTAR À TIROLESA INAPROPRIADAMENTE."},
    {resposta:"O PODER DO LADO NEGRO."},
    {resposta:"PEIDAR E SAIR."},
    {resposta:"TORNAR OS RIOS VERMELHOS COM O SANGUE DOS INFIÉIS."},
    {resposta:"SER CHATO COM CRIANÇAS."},
    {resposta:"FANTASMAS. "},
    {resposta:"CÂNCER. "},
    {resposta:"ROUBAR PIRULITO DE CRIANCINHA."},
    {resposta:"IMPLANTES DE SILICONE ASSIMÉTRICOS."},
    {resposta:"ENFIAR NA BUNDA. "},
    {resposta:"COLOCAR ARMADILHAS EM CASA PRA PEGAR ASSALTANTES."},
    {resposta:"AXÉ. "},
    {resposta:"XUXU. "},
    {resposta:"ALLAHU AKBAR! "},
    {resposta:"TREPAR."},
    {resposta:"PIX."},
    {resposta:"MASTURBAÇÃO FEMININA."},
    {resposta:"GERALMENTE NÃO FAZER A MÍNIMA IDEIA DO QUE ESTÁ ACONTECENDO."},
    {resposta:"MORRER."},
    {resposta:"DINHEIRO NA CUECA."},
    {resposta:"3,7 BILHÕES DE ANOS DE EVOLUÇÃO."},
    {resposta:"FURACÃO KATRINA."},
    {resposta:"SACOLÉ. "},
    {resposta:"SEGURAR UMA CRIANÇA E PEIDAR NA CABEÇA DELA."},
    {resposta:"GAYS."},
    {resposta:"BRUTALIDADE POLICIAL."},
    {resposta:"MIJAR NA BUNDA DE UMA GAROTA PRA FAZER UM BEBÊ."},
    {resposta:"A LOUCURA DO HOMEM."},
    {resposta:"FLANELINHAS."},
    {resposta:"PESSOAS MARRONS. "},
    {resposta:"HOMENS. "},
    {resposta:"O CACHORRO QUENTE QUE EU COLOQUEI NA MINHA VAGINA, 10 DIAS ATRÁS."},
    {resposta:"ESCALPELAMENTO. "},
    {resposta:"UMA FESTA VEGANA DESPROVIDA DE QUALQUER DIVERSÃO."},
    {resposta:"OVOS DE PTERODÁCTILO."},
    {resposta:"PASTEL DE FLANGO. "},
    {resposta:"O QUE FAZER COM TODO ESSE CHOCOLATE NO MEU PÊNIS."},
    {resposta:"DINÂMICA DE GRUPO."},
    {resposta:"LIMINHA. "},
    {resposta:"UM POSSÍVEL MUÇULMANO."},
    {resposta:"UM TUMOR CEREBRAL."},
    {resposta:"TWITTAR. "},
    {resposta:"O BIG BANG. "},
    {resposta:"O SOTAQUE CARIOCA. "},
    {resposta:"TER MEDO DE SI PRÓPRIO."},
    {resposta:"TER HERPES VAGINAL."},
    {resposta:"DURAR 1 MINUTO. "},
    {resposta:"TESOUROS ALÉM DE SEUS MAIORES SONHOS."},
    {resposta:"UMA MASTURBAÇÃO TRISTE."},
    {resposta:"O TAMANHO DO MEU PÊNIS."},
    {resposta:"O ENTREGADOR DE PIZZA."},
    {resposta:"JUSTAMENTE O QUE VOCÊ ESPERARIA."},
    {resposta:"10 INCRÍVEIS FATOS SOBRE O ÂNUS."},
    {resposta:"DIZER O QUE PENSA."},
    {resposta:"TER MEDO DE MULHER."},
    {resposta:"ESPERAR UM ARROTO E ACABAR VOMITANDO NO CHÃO."},
    {resposta:"DAR A LUZ AO ANTICRISTO."},
    {resposta:"LULA."},
    {resposta:"BOLSONARO."},
    {resposta:"CLOROQUINA."},
    {resposta:"GARDENAL."},
    {resposta:"ENGRAVIDAR COM O DEDO."},
    {resposta:"FINALMENTE TERMINAR DE ELIMINAR OS ÍNDIOS."},
    {resposta:"O QUE EU TÔ FAZENDO AQUI?"},
    {resposta:"CÉLULAS TRONCO. "},
    {resposta:"SOMBRIAS E MISTERIOSAS FORÇAS ALÉM DO NOSSO CONTROLE."},
    {resposta:"ARREPENDIDO. "},
    {resposta:"VESTIR-SE DE MODO A EXIBIR A LATERAL DOS SEIOS COM ELEGÂNCIA."},
    {resposta:"O QUÃO FODA EU SOU."},
    {resposta:"COM O CÚ NA MÃO."},
    {resposta:"SEXO ENTRE PANDAS. "},
    {resposta:"TRÊS SEGUNDOS CONSECUTIVOS DE FELICIDADE."},
    {resposta:"CREDO QUE DELÍCIA."},
    {resposta:"LOBOTOMIA. "},
    {resposta:"PESSOAS GOSTOSAS. "},
    {resposta:"DEDO NO CÚ E GRITARIA."},
    {resposta:"TOM CRUISE. "},
    {resposta:"ALGUM TIPO DE ASIÁTICO."},
    {resposta:"MENÁGE COM ANIMAIS."},
    {resposta:"HERPES LABIAL. "},
    {resposta:"O PREPÚCIO. "},
    {resposta:"CAGAR NO PAU."},
    {resposta:"CACHALOTES. "},
    {resposta:"SARCASMO AMBÍGUO."},
    {resposta:"CANAVIAL DE ROLA."},
    {resposta:"CHACOTA. "},
    {resposta:"O MILAGRE DO NASCIMENTO."},
    {resposta:"DANÇAR NA BOQUINHA DA GARRAFA."},
    {resposta:"MORADORES DE RUA."},
    {resposta:"ESPERAR ATÉ O CASAMENTO."},
    {resposta:"PENTADA VIOLENTA."},
    {resposta:"DAR UNS AMASSOS. "},
    {resposta:"A ÁFRICA. "},
    {resposta:"OSAMA BIN LADEN."},
    {resposta:"INCESTO. "},
    {resposta:"UMA PUNHETA TRISTE."},
    {resposta:"O BOZO."},
    {resposta:"EJACULAÇÃO PRECOCE."},
    {resposta:"DOIS ANÕES CAGANDO EM UM BALDE."},
    {resposta:"CRACK."},
    {resposta:"UM MÍMICO TENDO UM AVC."},
    {resposta:"TRAPACEAR NAS PARAOLIMPÍADAS."},
    {resposta:"SERIA MEU SONHO?"},
    {resposta:"PAGAR O PREÇO DE FERRO."},
    {resposta:"RABO ENTRE AS PERNAS."},
    {resposta:"DEUS. "},
    {resposta:"BATER UMA PUNHETA PARA UM GOLFINHO."},
    {resposta:"SE FUDEU."},
    {resposta:"COÇAR SOB AS DOBRAS DA PELE."},
    {resposta:"PELA CIÊNCIA. "},
    {resposta:"POSIÇÃO TESOURA. "},
    {resposta:"FUDIDO."},
    {resposta:"MACACO."},
    {resposta:"UROFILIA. "},
    {resposta:"TODO ESSE LÍQUIDO NA MINHA BOCA."},
    {resposta:"MACONHEIRO."},
    {resposta:"EMOÇÕES. "},
    {resposta:"LAMBER COISAS PARA ESTABELECER QUE SÃO PROPRIEDADE SUA."},
    {resposta:"PROPAGANDA ESQUERDISTA."},
    {resposta:"COMEU COCÔ?"},
    {resposta:"LITERALMENTE COMER UMA GRÁVIDA."},
    {resposta:"CERVEJA QUENTE. "},
    {resposta:"O SALÁRIO MÍNIMO. "},
    {resposta:"TRANSAR COM UM URSO. "},
    {resposta:"FICAR INVISIVEL NO ESCURO. "},
    {resposta:"UM CAGÃO."},
    {resposta:"A PLACENTA. "},
    {resposta:"O BIGODE DE HITLER."},
    {resposta:"ESTAR PEGANDO FOGO."},
    {resposta:"COMBUSTÃO ESPONTÂNEA."},
    {resposta:"MINHA APARENTE INABILIDADE DE LER ALGUMAS PALAVRAS SIMPLES EM VOZ ALTA."},
    {resposta:"RACISMO."},
    {resposta:"AMIZADE COLORIDA. "},
    {resposta:"A MACIA E PERFEITA PELE DE UMA CRIANÇA."},
    {resposta:"UM MICROPÊNIS."},
    {resposta:"PINTAR COM OS DEDOS."},
    {resposta:"A CONSTRUÇÃO SOCIAL PATRIARCAL DA GENITÁLIA FÍSICA."},
    {resposta:"CHEIRO DE PESSOA VELHA."},
    {resposta:"O REVERENDO. "},
    {resposta:"O SOFRIMENTO DA CLASSE MÉDIA."},
    {resposta:"MORRER DE DISENTERIA."},
    {resposta:"ACORDAR PELADO NO ESTACIONAMENTO DO BAHAMAS 24HRS."},
    {resposta:"INSINUAÇÕES CLASSISTAS."},
    {resposta:"MEUS DEMÔNIOS INTERIORES."},
    {resposta:"PRIVILÉGIO BRANCO. "},
    {resposta:"BATER O CÓCCIX. "},
    {resposta:"MALHAR PARA PEGAR MULHER. "},
    {resposta:"CAGAR E ANDAR PARA O TERCEIRO MUNDO."},
    {resposta:"PISTOLA D'ÁGUA CHEIA DE URINA DE GATO."},
    {resposta:"ESPERANÇA. "},
    {resposta:"PEGAR MULHER CASADA. "},
    {resposta:"CHAMEGO. "},
    {resposta:"ENTRAR EM UM ESQUEMA DE PIRÂMIDE."},
    {resposta:"OS GAYS."},
    {resposta:"DIDI. "},
    {resposta:"O SOM DE UMA PUNHETA SENDO BATIDA NO ESCURO."},
    {resposta:"ESCRAVIDÃO."},
    {resposta:"A CRÔNICA. "},
    {resposta:"LIMPEZA ÉTNICA. "},
    {resposta:"ENSINO MÉDIO."},
    {resposta:"RINHA DE GALO. "},
    {resposta:"PEIDO DE BUCETA. "},
    {resposta:"UM PIRULITÃO."},
    {resposta:"FOGO AMIGO. "},
    {resposta:"CAIR DE UMA ESCADA ROLANTE."},
    {resposta:"ESCOLAS PÚBLICAS."},
    {resposta:"FERNANDO COLLOR. "},
    {resposta:"PARA SEMPRE. "},
    {resposta:"ANOREXIA."},
    {resposta:"UMA FESTA DE ANIVERSÁRIO DECEPCIONANTE."},
    {resposta:"A RABETA. "},
    {resposta:"O BAIANO"},
    {resposta:"TRABALHADOR."},
    {resposta:"UMA MULHER ATREVIDA."},
    {resposta:"MINHA VIDA SEXUAL."},
    {resposta:"ATLETA DE OLIMPÍADA DE MATEMÁTICA."},
    ]

module.exports = respostas;